#!/bin/bash

BASE_URL="http://localhost:3001/api"

echo "NEXUS API TEST COMMANDS"
echo "======================="
echo ""
echo "# Health check"
echo "curl $BASE_URL/../health"
echo ""
echo "# Register"
echo "curl -X POST $BASE_URL/auth/register -H 'Content-Type: application/json' -d '{\"username\":\"test\",\"email\":\"test@test.com\",\"password\":\"Test123456\",\"displayName\":\"Test\"}'"
echo ""
echo "# Login"
echo "curl -X POST $BASE_URL/auth/login -H 'Content-Type: application/json' -d '{\"email\":\"test@test.com\",\"password\":\"Test123456\"}'"
echo ""
echo "# Create space (with token)"
echo "curl -X POST $BASE_URL/spaces -H 'Content-Type: application/json' -H 'Authorization: Bearer YOUR_TOKEN' -d '{\"name\":\"My Space\",\"description\":\"Test\",\"visibility\":\"PUBLIC\"}'"
echo ""
echo "# List spaces"
echo "curl $BASE_URL/spaces"
echo ""
echo "# Create post"
echo "curl -X POST $BASE_URL/posts -H 'Content-Type: application/json' -H 'Authorization: Bearer YOUR_TOKEN' -d '{\"title\":\"Hello\",\"content\":\"World\",\"spaceSlug\":\"my-space\",\"type\":\"TEXT\"}'"
echo ""
